DROP TABLE IF EXISTS URL;
CREATE TABLE URL(
                              ID BIGSERIAL PRIMARY KEY NOT NULL,
                              LONG_URL VARCHAR(256) NOT NULL,
                              SHORT_URL VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX SHORT_URL_INDEX on URL(SHORT_URL);
CREATE UNIQUE INDEX LONG_URL_INDEX on URL(LONG_URL);