DROP TABLE IF EXISTS RANDOM1;
CREATE TABLE RANDOM1(
                    ID BIGSERIAL PRIMARY KEY NOT NULL,
                    LONG_URL VARCHAR(256) NOT NULL,
                    SHORT_URL VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX SHORT_URL_INDEX_RD1 on RANDOM1(SHORT_URL);
CREATE UNIQUE INDEX LONG_URL_INDEX_RD1 on RANDOM1(LONG_URL);

DROP TABLE IF EXISTS RANDOM2;
CREATE TABLE RANDOM2(
                        ID BIGSERIAL PRIMARY KEY NOT NULL,
                        LONG_URL VARCHAR(256) NOT NULL,
                        SHORT_URL VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX SHORT_URL_INDEX_RD2 on RANDOM2(SHORT_URL);
CREATE UNIQUE INDEX LONG_URL_INDEX_RD2 on RANDOM2(LONG_URL);

DROP TABLE IF EXISTS BASE62;
CREATE TABLE BASE62(
                        ID BIGSERIAL PRIMARY KEY NOT NULL,
                        LONG_URL VARCHAR(256) NOT NULL
);
CREATE UNIQUE INDEX LONG_URL_INDEX_BS on RANDOM2(LONG_URL);

